### ISSUE TITLE
Variadic (Rest) Parameters

### ISSUE THREAD

**Issue by pr0me** [ShiftLeftSecurity/js2cpg#176]
js2cpg does not seem to correctly recognize javascript's variadic arguments.

Example:
```javascript
function sum(...num){
    num.forEach(alert);
};
```

Input: `cpg.method("sum").parameter.l`
Output: 
```scala
List[MethodParameterIn] = List(
  MethodParameterIn(
    id -> 1000113L,
    code -> "this",
    columnNumber -> Some(value = 0),
    dynamicTypeHintFullName -> ArraySeq(),
    evaluationStrategy -> "BY_VALUE",
    index -> 0,
    isVariadic -> false,
    lineNumber -> Some(value = 1),
    name -> "this",
    order -> 0,
    typeFullName -> "ANY"
  )
)
```
Expected: An additional `MethodParameterIn` with `name -> "num"` and `isVariadic -> true`.

**Comment by max-leuthaeuser** [comment]
Yes, this is something js2cpg can't do as those rest parameters are lowered away by the parser.
The new frontend (joern/jssrc2cpg) handles that (see: https://github.com/joernio/joern/blob/master/joern-cli/frontends/jssrc2cpg/src/test/scala/io/joern/jssrc2cpg/passes/AstCreationPassTest.scala#L737).
